root = "."  # Ensure this points to the root of your Go module
testdata_dir = "testdata"
tmp_dir = "api/tmp"

[build]
args_bin = []
bin = "api/tmp/main.exe"
cmd = "go build -o ./api/tmp/main.exe ./api"  # Point to the api directory where the main Go file is located
delay = 0
exclude_dir = [
    "assets",
    "configs",
    "deployments",
    "docker",
    "docs",
    "fern",
    "internal",
    "pkg",
    "policy",
    "services",
    "test",
    "website"
]  # Exclude directories that should not be watched
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["api"]  # Only include the api directory
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true