[package]
name = "env_config"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
