version: '3'

services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: "localstack/localstack:0.14.5"
    network_mode: bridge
    environment:
      - SERVICES=s3
    ports:
      - "4566:4566"
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: "bash -c 'AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test aws --endpoint-url=http://localhost:4566 s3 ls'"
      retries: 15
      interval: 10s

  pulsar:
    container_name: "autoscaler_pulsar"
    image: "apachepulsar/pulsar:latest"
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: bin/pulsar standalone

  redis:
    image: redis:7-alpine
    container_name: bull_redis
    ports:
      - "6379:6379"

#  clickhouse:
#    container_name: "autoscaler_clickhouse"
#    image: "clickhouse/clickhouse-server:latest"
#    environment:
#      - CLICKHOUSE_DB=autoscaler_clickhouse
#      - CLICKHOUSE_USER=user
#      - CLICKHOUSE_PASSWORD=password
#      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
#    ports:
#      - "18123:8123"
#      - "19000:9000"
#    volumes:
#      - /var/lib/clickhouse/
#      - /var/log/clickhouse-server/
#    ulimits:
#      nofile:
#        soft: 262144
#        hard: 262144
volumes:
  pulsardata:
  pulsarconf:
