
services:
  nats1:
    image: docker.io/nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - './data/nats/1:/data'
    command:
      - "--name=nats1"
      - "--cluster_name=c1"
      - "--cluster=nats://nats1:6222"
      - "--routes=nats-route://nats1:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

  cerbos:
    image: ghcr.io/cerbos/cerbos:0.37.0
    ports:
      - '3593:3593'
      - '3592:3592'
    volumes:
      - ../src/sal/policy:/policies

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    ports:
      - "3567:3567"
    environment:
      POSTGRESQL_CONNECTION_URI: postgresql://postgres:password@timescaledb:5432/postgres
    depends_on:
      - timescaledb
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
#      POSTGRES_DB: supertokens
    volumes:
      - './data/postgres:/var/lib/postgresql/data'

