# .github/workflows/ci.yml

name: On Merge MAIN

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_DOCKER_USERNAME: ${{ secrets.GH_DOCKER_USERNAME }}
      GH_DOCKER_TOKEN: ${{ secrets.GH_DOCKER_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - uses: actions/checkout@v4

      - name: Docker Login
        run: docker login ghcr.io --username "$GH_DOCKER_USERNAME" --password "$GH_DOCKER_TOKEN"

      - name: Run build
        run: earthly --ci --push +build-all-images